### ISSUE TITLE
Deploy Influx and Graphana.

### ISSUE THREAD

**Issue by P2W2** [citlab/gardening-adventure#10]
First Deployment on AWS Instance.
And connect first Sensor Data to it.

**Comment by P2W2** [comment]
### Grafana
* Host:  see AWS Console
Port: 3000

* Username: admin
Password: dspj2020
### InfluxDB
* Host: see AWS Console
Port: 8086

* Admin Username: gardener
Admin Password: dspj20192020

* Database: garden
* Username: grafana
Password: graf2020

**Comment by P2W2** [comment]
### Useful links:
* https://towardsdatascience.com/get-system-metrics-for-5-min-with-docker-telegraf-influxdb-and-grafana-97cfd957f0ac
* https://docs.influxdata.com/influxdb/v1.7/introduction/getting-started/

Docker files:
* https://hub.docker.com/_/influxdb/
* https://hub.docker.com/r/grafana/grafana

### Start InfluxDB & Grafana:
* Create Docker Network:
`docker network create gardening`

* InfluxDB initialization: 
`docker run --rm -p 8086:8086 -v influxdb-volume:/var/lib/influxdb --network gardening --name influxdb -e INFLUXDB_DB=garden -e INFLUXDB_ADMIN_ENABLED=true -e INFLUXDB_ADMIN_USER=gardener -e INFLUXDB_ADMIN_PASSWORD=dspj20192020 -e INFLUXDB_USER=grafana -e INFLUXDB_USER_PASSWORD=graf2020  influxdb  /init-influxdb.sh`
 
* Start InfluxDB:
`docker run -d -p 8086:8086 -v influxdb-volume:/var/lib/influxdb --restart always --network gardening --name influxdb influxdb`

* Start Grafana:
`docker run -d -p 3000:3000 -v grafana-volume:/var/lib/grafana --restart always --network gardening --name grafana grafana/grafana`

**Comment by rajasiman** [comment]
the public dns might change after every restart. right now it is 
ec2-3-125-42-20.eu-central-1.compute.amazonaws.com

would be optimal to check the dns after starting the instance everytime.
fyi
