### ISSUE TITLE
Pre configurated Raspberry pi Image.

### ISSUE THREAD

**Issue by rajasiman** [citlab/gardening-adventure#11]
Batman, SSH etc.

**Comment by rajasiman** [comment]
https://medium.com/swlh/headless-raspberry-pi-part-1-installing-configuring-raspbian-b8714a767259

**Comment by rajasiman** [comment]
https://medium.com/platformer-blog/creating-a-custom-raspbian-os-image-for-production-3fcb43ff3630

More like configure everything on one and clone the image to other devices.

**Comment by rajasiman** [comment]
https://www.raspberrypi.org/blog/pibakery/

**Comment by rajasiman** [comment]
https://github.com/RPi-Distro/pi-gen
https://learnthinksolvecreate.wordpress.com/category/raspberry-pi/pi-gen/
http://kmdouglass.github.io/posts/create-a-custom-raspbian-image-with-pi-gen-part-1/

**Comment by rajasiman** [comment]
https://github.com/TheSin-/rpi-img-builder

This looks _**very**_ promising. 

Plugins:
It should be fairly easy to customize your image for your own needs. Building and adding plugins is easy. Each plugin can contain:

- packages: file with one line containing debian packages to install
- preinst: script to run pre chroot
- postinst: script to run in chroot of the rootfs
- files: dir which contains files to be copied into the rootfs, perms and atts included
- patches: dir which contains patch files to apply to the rootfs
- baseonly: is a special file for repo plugins, if the file exists the plugin is only included if the repo is the base repo

**Comment by rajasiman** [comment]
https://raspberrypi.stackexchange.com/questions/855/is-it-possible-to-update-upgrade-and-install-software-before-flashing-an-image

**Comment by shri-hari93** [comment]
Custom Pi image
- [ ] Latest pi OS image 
- [ ] Enable SSH
- [ ] Batman installation
- [ ] Gateway configuration / Node configuration 
- [ ] Initiate batman interface using script
- [ ] Assign Ip address (dhcp/avahi-autoipd)
- [ ] Install K3S agent using token

**Comment by srnbckr** [comment]
Are there any updates on this?

**Comment by shri-hari93** [comment]
@srnbckr I have created a couple of images will have to test with k3s cluster tomorrow at your office.
