### ISSUE TITLE
Technology decisions/additions

### ISSUE THREAD

**Issue by rajasiman** [citlab/gardening-adventure#17]
Should we look at using the TICK stack? At the very least the T along with the I from TICK.

Telegraf (Developed by Influxdata)
> https://www.influxdata.com/time-series-platform/telegraf/
**IoT sensors**
Collect critical stateful data (pressure levels, temp levels, etc.) from IoT sensors and devices.
**Systems**
Collect metrics from your modern stack of cloud platforms, containers, and orchestrators.

Message Queue:
> https://www.rabbitmq.com/
**Asynchronous Messaging**
Supports multiple messaging protocols, message queuing, delivery acknowledgement, flexible routing to queues, multiple exchange type.

All of the stuff listed above makes it A LOT easier for us.

**Comment by rajasiman** [comment]
Also what about this... Oops.

https://docs.influxdata.com/platform/integrations/kubernetes/#should-i-run-influxdb-in-kubernetes

**Comment by P2W2** [comment]
MIGT Stack --> mqtt, influxDB, Grafana, telegraf
:)
