### ISSUE TITLE
kubernetes deployment testing

### ISSUE THREAD

**Issue by rajasiman** [citlab/gardening-adventure#18]

**Comment by rajasiman** [comment]
http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/role?namespace=default

Dashboard URL

**Comment by shri-hari93** [comment]
> http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/role?namespace=default
> 
> Dashboard URL

is it a suggestion for dashboard url??

**Comment by rajasiman** [comment]
thats the default kubernetes dashboard URL, not what we would have to setup.
