### ISSUE TITLE
Configure Kubernetes Environment

### ISSUE THREAD

**Issue by P2W2** [citlab/gardening-adventure#34]
Deploy:
Grafana, telegraf, influxDB and Mosquitto-mqtt on the master node.

Deploy sensor Docker images on the raspberry's pi

**Comment by P2W2** [comment]
## Assosiate Node with pod
`kubectl label nodes peewee-thinkpad dasboard=grafana --overwrite
`
## Grafana
`helm install grafana-garden -f grafana.yaml --set nodeSelector.dasboard=grafana stable/grafana
`
## InfluxDB
`helm install influxdd-garden -f influxdb.yaml --set nodeSelector.databases=influxdb stable/influxdb
`
## Mosquitto 
`helm install mosquitto-garden -f mosquitto.yaml --set nodeSelector.mqttt=mosquitto smizy/mosquitto
`
`kubectl expose pod ll mosquitto-garden... --port=1883 --target-port=188
`
## Telegraf
`helm install telegraf-garden -f telegraf.yaml stable/telegraf`

**Comment by rajasiman** [comment]
https://github.com/smizy/charts/issues/4

FYI
