### ISSUE TITLE
Install K3s

### ISSUE THREAD

**Issue by P2W2** [citlab/gardening-adventure#5]
Install k3s on Pi's and get familiar with deployment workflow, kubectl and so on

We plan to use k3s for the Kubernetes cluster deployed on all Pi's and the central server, you can use the following links
to read up on k3s:

https://k3s.io/ -> Project Website with documentation on how to deploy k3s
https://github.com/rancher/k3os -> Linux distribution designed to run k3s
https://github.com/alexellis/k3sup -> can be used to deploy k3s on VM's and other devices
Some Blogposts describing the deployment of k3s on Raspberry Pi's:
https://medium.com/@mabrams_46032/kubernetes-on-raspberry-pi-c246c72f362f https://www.danielstechblog.io/running-a-kubernetes-cluster-with-k3s-on-raspbian/
* http://collabnix.com/get-started-with-k3s-a-lightweight-kubernetes-distribution-for-raspberry-pi-cluster/

Some Blogposts about deploying a Mesh network with Raspberry Pi's:
https://medium.com/swlh/setting-up-an-ad-hoc-mesh-network-with-raspberry-pi-3b-using-batman-adv-1c08ee565165 https://medium.com/@tdoll/how-to-setup-a-raspberry-pi-ad-hoc-network-using-batman-adv-on-raspbian-stretch-lite-dce6eb896687
https://tomesh.net/build-a-node/ https://hackaday.com/2012/11/14/mesh-networking-with-multiple-raspberry-pi-boards/

In case of questions or problems feel free to drop us a mail.

**Comment by alexellis** [comment]
Let me know if I can be of help. #k3sup is a nice tool for installing k3sup, but also helm charts after that.
