### ISSUE TITLE
please check for the red marked sensors in the google docs, if you can find appropiate sensors on the following sides:

### ISSUE THREAD

**Issue by P2W2** [citlab/gardening-adventure#9]
[GooGle Doc](https://docs.google.com/document/d/1Rr977Y6NMDTuLg9P6otBDmeE8tLGlXRtDigQU-5CEXU/edit?usp=sharing​)
[Google Doc with Item Links](https://docs.google.com/document/d/1kNQiLh6pq2x9lESNbOEtW0LJluIDak8VAkCuGwdTtOM/edit?usp=sharing)
----------------Sites--------------------
https://www.adafruit.com/, https://eckstein-shop.de/, https://www.ti.com/, https://www.mouser.de, reichelt and conrad are also okay.

**Comment by rajasiman** [comment]
waiting on florian's reply, we still do not know the list of parts already ordered. Once that i clear, we can filter the not yet ordered stuff.

**Comment by rajasiman** [comment]
After yesterday's discussion with Florian, I think we have all of it ordered. I will close this ticket.
